const Distance = Object.freeze({
    Nanometer: "nanometer",
    Micrometer: "micrometer",
    Millimeter: "millimeter",
    Centimeter: "centimeter",
    Meter: "meter",
    Kilometer: "kilometer",
    NauticalMile: "nautical-mile",
    Inch: "inch",
    Foot: "foot",
    Yard: "yard",
    Mile: "mile",
});

const Area = Object.freeze({
    SquareCentimeter: "square-centimeter",
    SquareMeter: "square-meter",
    SquareFoot: "square-foot",
    SquareInch: "square-inch",
    Acre: "acre",
    Hectare: "hectare",
});

const Volume = Object.freeze({
    Milliliter: "milliliter",
    Centiliter: "centiliter",
    Deciliter: "deciliter",
    Liter: "liter",
    Kiloliter: "kiloliter",
    Decaliter: "decaliter",
    Hectoliter: "hectoliter",
    CubicMillimeter: "cubic-millimeter",
    CubicCentimeter: "cubic-centimeter",
    CubicMeter: "cubic-meter",
    CubicInch: "cubic-inch",
    FluidOnce: "fluid-once",
    Gill: "gill",
    Pint: "pint",
    Quart: "quart",
    Gallon: "gallon",
});

const distance = [
    "nanometer",
    "nm",
    "micrometer",
    "millimeter",
    "mm",
    "centimeter",
    "cm",
    "meter",
    "m",
    "kilometer",
    "km",
    "nautical-mile",
    "nmi",
    "inch",
    "foot",
    "ft",
    "yard",
    "yd",
    "mile",
    "mi",
];
const area = [
    "square-centimeter",
    "cm2",
    "square-foot",
    "ft2",
    "square-inch",
    "2inch",
    "2in",
    "square-meter",
    "2m",
    "acre",
    "hectare",
];
const volume = [
    "milliliter",
    "ml",
    "centiliter",
    "cl",
    "deciliter",
    "dl",
    "liter",
    "l",
    "kiloliter",
    "kl",
    "decaliter",
    "dal",
    "hectoliter",
    "hl",
    "cubic-millimeter",
    "3mm",
    "cubic-centimeter",
    "3cm",
    "cubic-meter",
    "3m",
    "cubic-inch",
    "3inch",
    "fluid-ounce",
    "floz",
    "gill",
    "pint",
    "quart",
    "gallon",
];
const units = [
    "K",
    "F",
    "C",
    "Kelvin",
    "Fahrenheit",
    "Celsius",
    "kelvin",
    "celsius",
    "fahrenheit",
    "k",
    "f",
    "c",
];
module.exports = { Distance, Area, Volume, distance, area, volume, units };
